### PR TITLE
[NEW] Set leaderboard start date

### PR DESCRIPTION
**Pull request by djcruz93**
Introduces the capability to set the starting date for the leaderboard. All the stats on the leaderboard will be displayed counting all the PRs and Issues created after the selected start date.

### CODE REVIEW

**Review by lolimay — APPROVED** [review]
Nice!

**Comment by RonLek** [comment]
@djcruz93 there seem to be some merge conflicts in `API.js`. Can you please resolve them?

**Review by RonLek — APPROVED** [review]
lgtm!

**Comment by djcruz93** [comment]
@lolimay once the PR#48 gets merged, I'll rebase this PR to the updated master, which will then automatically resolve conflicts.

**Comment by lolimay** [comment]
> @lolimay once the [PR#48](https://github.com/RocketChat/GSoC-Contribution-Leaderboard-Node/pull/48) gets merged, I'll rebase this PR to the updated master, which will then automatically resolve conflicts.

done. Please do!

**Pull request merged**
